#!/usr/bin/sh

wmname LG3D &
sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_poiner true
bspc config pointer_follows_focus false
bspc config focused_border_color "#51afef"

#AutoStart
#picom &					# composer
nitrogen --restore & 			# wallpaper
dunst & 				# notify daemon
$HOME/.config/polybar/launch.sh		# polybar
setxkbmap us -variant dvorak-intl	# keyboard distribution

#vm - resolution arandr
xrandr --output $(xrandr | grep " connected" | awk '{ print $1 }') --mode 1920x1080 --pos 0x0 --rotate normal

# virtualbox clipboard
VBoxClient --clipboard
VBoxClient --draganddrop
