#!/usr/bin/env bash
# Directorio de iconos y función de notificación
micro_dir="$HOME/.config/bspwm/src/assets"
notify() {
    dunstify -u low -h string:x-dunst-stack-tag:cmicrophone "$@"
}

# Get volume status
get_status() {
    local status=$(pactl get-source-mute @DEFAULT_SOURCE@ | cut -d " " -f 2)
    [[ $status == yes ]] && echo "muted" || echo "unmuted"
}

# Determine icon based on status
get_icon() {
    local current_status=$(get_status)
    if [[ $current_status == muted ]]; then
        icon="$micro_dir/mute-mic.png"
    else
        icon="$micro_dir/unmute-mic.png"
    fi
    echo $icon
}

# Toggle mute
toggle_mute() {
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
    local icon=$(get_icon)
    local message=$(get_status)
    notify -i "$icon" "$message"
}

# Handle options
case $1 in
    toggle) toggle_mute ;;
    *)      echo "$(get_status)" ;;
esac
