#!/usr/bin/env bash

# Checks if a list ($1) contains an element ($2)
contains() {
    for e in $1; do
        [[ "$e" -eq "$2" ]] && echo 1 && return
    done
    echo 0
}

print_workspaces2() {
    buf=""
    desktops=$(bspc query -D -m "DP-1" --names)
    focused_desktop=$(bspc query -D -m "DP-1" -d focused --names)
    occupied_desktops=$(bspc query -D -m "DP-1" -d .occupied --names)

    for d in $desktops; do
        if [[ "$(contains "$focused_desktop" "$d")" -eq 1 ]]; then
            ws=$d
            icon="󰮯"
            class="workspace-focused"
        elif [[ "$(contains "$occupied_desktops" "$d")" -eq 1 ]]; then
            ws=$d
            icon="󰊠"
            class="workspace-occupied"
        else
            ws="$d"
            icon="󰑊"
            class="workspace-empty"
        fi

        buf+="(eventbox :cursor \"pointer\" (button :class \"$class\" :onclick \"bspc desktop -f $ws\" \"$icon\"))"
    done

    echo "(box :orientation \"v\" :class \"works\" :halign \"center\" :valign \"center\" :vexpand true :hexpand true $buf)"
}

# Listen to bspwm changes
print_workspaces2
bspc subscribe desktop node_transfer | while read -r _ ; do
    print_workspaces2 &
done
